" __     _____ __  __ ____   ____ 
" \ \   / /_ _|  \/  |  _ \ / ___|
"  \ \ / / | || |\/| | |_) | |    
"   \ V /  | || |  | |  _ <| |___ 
"    \_/  |___|_|  |_|_| \_\\____|
"                          - Phillip McAughan
 

" Line numbering
set number relativenumber
set number number

" Setting leader  to space 
" Doing the nnoremap so that it doesn't map to anything beforehand
nnoremap <Space> <Nop>
:let mapleader=" "

" using Pathogen to do all the plugins
execute pathogen#infect()
syntax on
filetype plugin indent on
filetype plugin on

" Things for autocomplete: some highlights -
" CTRL+n = any word
" CTRL+x CTRL+f for filenames
set omnifunc=syntaxcomplete#Complete

"adds recursive subdirectories to current path, used
"for ^x+^f file completion 
set path+=** 

" File manager (netrw) stuff
" Basically makes it act like NERDtree
let g:netrw_banner=0 "disable banner
let g:netrw_liststyle=3 "tree view
let g:netrw_browse_split=4 "splits when open
let g:netrw_winsize=25 "the split is smol when first opening


" Swap : and ; because I am a lazy bastard
" who does not wannt to bother pressing shift
" (Carpal tunnel doesn't sound fun)
nnoremap ; :
nnoremap : ;

" Make Q run the current line as a shell command
" and write the output
nnoremap Q !!$SHELL<CR>

"Tabs are 4 characters wide
set tabstop=4
set shiftwidth=4
set softtabstop=0 noexpandtab

"(Hopefully) use system keyboard
set clipboard^=unnamed

"Unicode
set encoding=UTF-8

" Q just force exits
command Q q!

"I hope this works
set tags+=./

" command Spellcheck set spelllang=en_us
"
" function! SpellcheckToggle()


nmap <F8> :TagbarToggle<CR>
