alias sai="sudo apt install"
alias sa="sudo apt"
alias s="sudo"
alias clc="clear"
alias sr="snap run"
alias g17="g++ -std=c++17"
alias ZZ="cd .."
alias ..="cd .."
alias c="g17 *.cpp"
alias cleak="g17 -pedantic -fsanitize=address,undefined *.cpp"
alias cweather="curl wttr.in"
alias vip="vim -p"
alias vimrc="vim ~/.vim/vimrc"
alias bashalias="vim ~/.bash_aliases"
alias mkv="mkdir -vp"
alias quit="exit"
alias diff="diff --color"
alias clera="clear"
alias celar="clear"
alias awesomerc="vim ~/.config/awesome/rc.lua"
alias oc="octave-cli"
alias iv="iverilog *.v"
alias home="cd ~"
alias p3="python3"
